name: Build Minecraft Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew (Windows)
      run: |
        Get-ChildItem -Path ./gradlew.bat | ForEach-Object { $_.IsReadOnly = $false }
        .\gradlew.bat tasks

    - name: Build with Gradle
      run: ./gradlew.bat build

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: mod-jar
        path: build/libs/*.jar
